openapi: 3.1.0
info:
  title: Test writeOnly/readOnly fields
  version: 1.0.0
paths:
  /test:
    get:
      requestBody:
        content:
          application/json:
            x-type:
              $ref: '#/components/x-types/Person'
            examples:
              Correct:
                value:
                  name:
                    first: string
                    last: string
              Incorrect:
                value:
                  id: uuid-like-id # not expected in response
                  name: First Last # must be an object
      responses:
        200:
          description: Test.
          content:
            application/json:
              x-type:
                $ref: '#/components/x-types/Person'
              examples:
                Correct:
                  value:
                    id: uuid-like-id
                    name: First Last
                Incorrect:
                  value:
                    name: # must be a string
                      first: Wrong
                      last: Wrong
                    # id is required

components:
  x-types:
    Id:
      $readonly: string::uuid
      not-allowed: $readonly and $writeonly must not have neighbours
    Name:
      $readonly: string
      $writeonly:
        first: string
        last: string
    Person:
      id:
        $ref: '#/components/x-types/Id'
      name:
        $ref: '#/components/x-types/Name'
